version: '3'

services:
  api_biotime:
    container_name: api-biotime-container  # Agrega el nombre del contenedor aquí
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'development'
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    restart: unless-stopped