version: '3'

services:
  api_biotime:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'development'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped
