version: '3'

services:
  api_biotime:
    container_name: api-biotime-container  # Agrega el nombre del contenedor aquí
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'development'
      DB_USER: 'postgres'
      DB_HOST: '192.168.1.8'
      DB_DATABASE: 'biotime'
      DB_PASSWORD: 'postgres'
      DB_PORT: 7496
    ports:
      - "8000:3000"
    volumes:
      - .:/app
    restart: unless-stopped